### ISSUE TITLE
Node.js Ensure a correct package name.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/toolkit#1615] opened 2017-10-12 18:01 UTC
Transform [this](https://github.com/googleapis/toolkit/pull/1614/files/986573343ff7d0ecded8e9a8b545bfe17e8df61d#r144363560) into an acceptable name. Perceivably this name can have a hyphen in it like shown in the multiple-services baseline, which would cause an error.

**Comment by eoogbe** [comment] 2017-11-29 02:31
Duplicate of #1075

**Closed by eoogbe** 2017-11-29 02:31 UTC
