### ISSUE TITLE
Find a way to keep toolkit and compilecheck in sync

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#84] opened 2016-05-10 19:40 UTC
Ideally all of the discovery files we have in testdata should always pass compilecheck. We should find a way to enforce this.

**Comment by bjwatson** [comment] 2016-06-20 21:24
@pongad Is this Discovery-specific?

**Comment by pongad** [comment] 2016-06-20 22:46
@bjwatson It is. Added the label. In this case, "compilecheck" refers to the tool we wrote to make sure discovery samples compile.

**Comment by bjwatson** [comment] 2016-06-21 00:58
Ok, thanks.

**Comment by saicheems** [comment] 2016-12-21 20:04
This is a duplicate of other bugs... and is being implemented

**Closed by saicheems** 2016-12-21 20:04 UTC
Labels: Discovery
