### ISSUE TITLE
NodeJS: Have config generator generate domain layer location for google cloud.

### ISSUE THREAD

**Issue by landrito** [googleapis/toolkit#1691] opened 2017-11-15 19:19 UTC
### What

We can semi reliably infer if an api is a google cloud api by checking if the proto package name of the service begins with `google.cloud`. When we come across this situation, the nodejs package name should have the domain layer location set to be `google-cloud`.

**Comment by landrito** [comment] 2017-11-15 19:20
@alexander-fenster This might be a good issue for you to take on if you want to get your feet wet in toolkit. Feel free to reassign to yourself! 😄

**Comment by eoogbe** [comment] 2017-11-29 02:40
Duplicate of #972

**Closed by eoogbe** 2017-11-29 02:40 UTC
